# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\dev\sticky\Encrypt-Sticky\Design\DeleteNoteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteNote(object):
    def setupUi(self, DeleteNote):
        DeleteNote.setObjectName("DeleteNote")
        DeleteNote.resize(250, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DeleteNote.sizePolicy().hasHeightForWidth())
        DeleteNote.setSizePolicy(sizePolicy)
        DeleteNote.setMinimumSize(QtCore.QSize(250, 130))
        DeleteNote.setMaximumSize(QtCore.QSize(250, 130))
        font = QtGui.QFont()
        font.setPointSize(7)
        DeleteNote.setFont(font)
        DeleteNote.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteNote)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(DeleteNote)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_yes = QtWidgets.QPushButton(self.frame)
        self.pushButton_yes.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_yes.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_yes.setFont(font)
        self.pushButton_yes.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color:rgb(67, 133, 200);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(17, 133, 195);\n"
"}")
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout.addWidget(self.pushButton_yes)
        self.pushButton_no = QtWidgets.QPushButton(self.frame)
        self.pushButton_no.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_no.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_no.setFont(font)
        self.pushButton_no.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color: rgb(229, 229, 229);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: lightgray;\n"
"}")
        self.pushButton_no.setObjectName("pushButton_no")
        self.horizontalLayout.addWidget(self.pushButton_no)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(DeleteNote)
        QtCore.QMetaObject.connectSlotsByName(DeleteNote)

    def retranslateUi(self, DeleteNote):
        _translate = QtCore.QCoreApplication.translate
        DeleteNote.setWindowTitle(_translate("DeleteNote", "Dialog"))
        self.label.setText(_translate("DeleteNote", "Do you want to delete this note?"))
        self.checkBox.setText(_translate("DeleteNote", "Don\'t ask again"))
        self.pushButton_yes.setText(_translate("DeleteNote", "Delete"))
        self.pushButton_no.setText(_translate("DeleteNote", "Cancel"))
