# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\dev\sticky\Encrypt-Sticky\Design\PasswordInputDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(309, 121)
        Dialog.setStyleSheet("#frame_button {\n"
"    background-color: rgb(255, 247, 209);\n"
"}\n"
"\n"
"#frame_container {\n"
"    background-color: rgb(255, 247, 209);\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    border: none;\n"
"    font: 14pt \"MingLiU-ExtB\";\n"
"    background-color: rgb(255, 247, 209);\n"
"}\n"
"\n"
"#frame_title {\n"
"    background-color: rgb(255, 242, 171);\n"
"}\n"
"\n"
"#frame, #edtPassword {\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(255, 242, 171);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:checked {\n"
"    background: rgb(237, 230, 194);\n"
"}")
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_title = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitle = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.frame.setFont(font)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(4)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("")
        self.btnClose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        self.btnClose.setIconSize(QtCore.QSize(20, 20))
        self.btnClose.setObjectName("btnClose")
        self.gridLayout_2.addWidget(self.btnClose, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout_3.addWidget(self.frame_title, 0, 0, 1, 1)
        self.frame_container = QtWidgets.QFrame(Dialog)
        self.frame_container.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.frame_container.setFont(font)
        self.frame_container.setStyleSheet("")
        self.frame_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_container.setObjectName("frame_container")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_container)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setHorizontalSpacing(4)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.edtPassword = QtWidgets.QLineEdit(self.frame_container)
        self.edtPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.edtPassword.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.edtPassword.setFont(font)
        self.edtPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.edtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtPassword.setObjectName("edtPassword")
        self.gridLayout_4.addWidget(self.edtPassword, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_container)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_container, 1, 0, 1, 1)
        self.frame_button = QtWidgets.QFrame(Dialog)
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.frame_button_2 = QtWidgets.QGridLayout(self.frame_button)
        self.frame_button_2.setContentsMargins(0, 0, 10, 4)
        self.frame_button_2.setSpacing(10)
        self.frame_button_2.setObjectName("frame_button_2")
        self.btnConfirm = QtWidgets.QPushButton(self.frame_button)
        self.btnConfirm.setMinimumSize(QtCore.QSize(80, 35))
        self.btnConfirm.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.btnConfirm.setFont(font)
        self.btnConfirm.setObjectName("btnConfirm")
        self.frame_button_2.addWidget(self.btnConfirm, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frame_button_2.addItem(spacerItem, 0, 0, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.frame_button)
        self.btnCancel.setMinimumSize(QtCore.QSize(80, 35))
        self.btnCancel.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.frame_button_2.addWidget(self.btnCancel, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_button, 2, 0, 1, 1)
        self.gridLayout_3.setRowStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.edtPassword, self.btnConfirm)
        Dialog.setTabOrder(self.btnConfirm, self.btnCancel)
        Dialog.setTabOrder(self.btnCancel, self.btnClose)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblTitle.setText(_translate("Dialog", "Encrypt Your Note"))
        self.label.setText(_translate("Dialog", "Password:"))
        self.btnConfirm.setText(_translate("Dialog", "Confirm"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
import images_rc
